//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIDemo.Models
{
    public partial class ExceptionLog
    {
        public string AP_ID { get; set; }
        public string Function_Name { get; set; }
        public System.DateTime Create_Time { get; set; }
        public string ErrorMsg { get; set; }
    }
}
